=== dangari/EwokWars/EwokWars/EwokWarsContent/Levels/level.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT level       ((hud, eventobjects, room+) |
					  (eventobjects, room+))>
<!ELEMENT eventobjects (portaldefinition*)  >
<!ELEMENT portaldefinition (model) >
<!ELEMENT model       (#PCDATA) >
<!ELEMENT room        (name, design, enemies) >
<!ELEMENT name        (#PCDATA) >
<!ELEMENT design      (background, walls, portals, movableobject*)>
<!ELEMENT background  (#PCDATA) >
<!ELEMENT walls       (#PCDATA) >

<!ELEMENT portals     (portal+)>
<!ELEMENT portal      (position)>
<!ELEMENT movableobject (position, model)>
<!ELEMENT position    (x, y) >
<!ELEMENT x           (#PCDATA) >
<!ELEMENT y           (#PCDATA) >

<!ELEMENT enemies     (enemy*)>
<!ELEMENT enemy       (position | patrolling) >
<!ELEMENT patrolling  ((position),(position+))>
<!ELEMENT hud		  EMPTY>


<!ATTLIST enemydefinition
    eId         NMTOKEN    #REQUIRED >
<!ATTLIST portaldefinition
    pId         NMTOKEN    #REQUIRED
    pPartnerId  NMTOKEN    #IMPLIED >
<!ATTLIST room
    rId         NMTOKEN    #REQUIRED
    width       NMTOKEN    #REQUIRED
    height      NMTOKEN    #REQUIRED >
<!ATTLIST portal
    pIdRef      NMTOKEN    #REQUIRED >
<!ATTLIST enemy 
    type  (battledroid|stormtrooper)    #REQUIRED 
	viewdirection (east|west|north|south) #IMPLIED>
<!ATTLIST hud 
    type  (Game|Debug|None) #REQUIRED>

=== dangari/EwokWars/EwokWars/EwokWarsContent/Levels/level1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE level SYSTEM "level.dtd">
<level>
	<hud type="Game" />
	
	<eventobjects>
		<!-- if you don't set the pPartnerId attribute, the portal can
		     be used only as a "one way portal" or "landing portal" -->
			 
		<!-- pId with value '0' defines the spawn point for Hero.
			 This "Entryportal" is not allowed to use another 
			 portal as partner but itself (this value will be ignored) -->
		<portaldefinition pId="0"> 
			<model>none</model>
		</portaldefinition>
		<portaldefinition pId="1" pPartnerId="101">
			<model>ladderDown</model>
		</portaldefinition>
		<portaldefinition pId="101" pPartnerId="1">
			<model>ladderUp</model>
		</portaldefinition>
		<portaldefinition pId="2" pPartnerId="102">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="102">
			<model>none</model>
		</portaldefinition>
		<portaldefinition pId="3" pPartnerId="103">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="103" pPartnerId="3">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="4" pPartnerId="104">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="104">
			<model>none</model>
		</portaldefinition>
		<portaldefinition pId="5" pPartnerId="105">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="105">
			<model>none</model>
		</portaldefinition>
		<portaldefinition pId="106" pPartnerId="0">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="107" pPartnerId="0">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="108" pPartnerId="5">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="109" pPartnerId="103">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="10" pPartnerId="110">
			<model>portal</model>
		</portaldefinition>
		<portaldefinition pId="110">
			<model>none</model>
		</portaldefinition>
	</eventobjects>

	<!-- The room with rId="0" defines the entry room -->
	<room rId="0" width="1000" height="1000">
		<name>Room 1 - Kill all enemys in the last room to finish the game!</name>
		
		<design>
			<background>Background_Stone</background>
			<walls>Wall_Stone</walls>
			<portals>
				<portal pIdRef="0"> <!-- This is where the Hero will spawn -->
					<position>
						<x>150</x>
						<y>150</y>
					</position>
				</portal>
				<portal pIdRef="1">
					<position>
						<x>150</x>
						<y>850</y>
					</position>
				</portal>
				<portal pIdRef="2">
					<position>
						<x>900</x>
						<y>900</y>
					</position>
				</portal>
			</portals>
		</design>

		<enemies>
			<enemy type="stormtrooper" viewdirection="south"> 
			<!--                        ^   (south / north == vertical; east / west == horizontal) 
											default is "south"
			-->
				<position>
					<x>700</x>
					<y>150</y>
				</position>
			</enemy>
			<enemy type="battledroid">
				<patrolling>
					<position>
						<x>150</x>
						<y>700</y>
					</position>
					<position>
						<x>400</x>
						<y>700</y>
					</position>
					<position>
						<x>400</x>
						<y>900</y>
					</position>
					<position>
						<x>400</x>
						<y>700</y>
					</position>
				</patrolling>	
			</enemy>
		</enemies>
	</room>
	
	<room rId="1" width="1500" height="1500">
		<name>Room 1 - Basement</name>
		
		<design>
			<background>Background_Stone</background>
			<walls>Wall_Stone</walls>
			<portals>
				<portal pIdRef="101">
					<position>
						<x>150</x>
						<y>1200</y>
					</position>
				</portal>	
				<portal pIdRef="3">
					<position>
						<x>1200</x>
						<y>300</y>
					</position>
				</portal>		
				<portal pIdRef="103">
					<position>
						<x>1250</x>
						<y>1250</y>
					</position>
				</portal>		
				<portal pIdRef="104">
					<position>
						<x>1400</x>
						<y>300</y>
					</position>
				</portal>				
			</portals>
			<movableobject>
				<position>
					<x>200</x>
					<y>600</y>
				</position>
				<!-- ATM modeltype 'hayBale' is the only one that is supported -->
				<model>hayBale</model> 
			</movableobject>
		</design>

		<enemies>
			<enemy type="battledroid" viewdirection="east">
				<position>
					<x>200</x>
					<y>500</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="east">
				<position>
					<x>200</x>
					<y>700</y>
				</position>
			</enemy>
			<enemy type="battledroid">
				<patrolling>
					<position>
						<x>730</x>
						<y>200</y>
					</position>
					<position>
						<x>730</x>
						<y>1300</y>
					</position>
				</patrolling>	
			</enemy>
			<enemy type="battledroid">
				<patrolling>
					<position>
						<x>850</x>
						<y>1300</y>
					</position>
					<position>
						<x>850</x>
						<y>200</y>
					</position>
				</patrolling>	
			</enemy>
		</enemies>
	</room>
	
	<room rId="2" width="1500" height="1500">
		<name>Room 2</name>
		
		<design>
			<background>Background_Stone</background>
			<walls>Wall_Stone</walls>
			<portals>
				<portal pIdRef="102">
					<position>
						<x>1150</x>
						<y>1200</y>
					</position>
				</portal>
				<portal pIdRef="4">
					<position>
						<x>600</x>
						<y>600</y>
					</position>
				</portal>
				<portal pIdRef="5">
					<position>
						<x>1300</x>
						<y>200</y>
					</position>
				</portal>
			</portals>
			<movableobject>
				<position>
					<x>200</x>
					<y>600</y>
				</position>
				<!-- ATM modeltype 'hayBale' is the only one that is supported -->
				<model>hayBale</model> 
			</movableobject>
		</design>

		<enemies>
			<enemy type="stormtrooper" viewdirection="west"> 
			<!--                        ^   (south / north == vertical; east / west == horizontal) 
											default is "south"
			-->
				<position>
					<x>250</x>
					<y>300</y>
				</position>
			</enemy>
			<enemy type="stormtrooper" viewdirection="west"> 
				<position>
					<x>1250</x>
					<y>800</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="west">
				<position>
					<x>1300</x>
					<y>600</y>
				</position>
			</enemy>
		</enemies>
	</room>
	
	<room rId="3" width="1500" height="1500">
		<name>Room 3 - You've almost made it!</name>
		
		<design>
			<background>Background_Stone</background>
			<walls>Wall_Stone</walls>
			<portals>
				<portal pIdRef="105">
					<position>
						<x>750</x>
						<y>750</y>
					</position>
				</portal>	
				<!--<portal pIdRef="106">
					<position>
						<x>250</x>
						<y>250</y>
					</position>
				</portal>-->
				<portal pIdRef="108">
					<position>
						<x>1300</x>
						<y>200</y>
					</position>
				</portal>	
				<portal pIdRef="109">
					<position>
						<x>1300</x>
						<y>1300</y>
					</position>
				</portal>		
				<portal pIdRef="10">
					<position>
						<x>250</x>
						<y>1300</y>
					</position>
				</portal>					
			</portals>
		</design>

		<enemies>
			<enemy type="battledroid">
				<patrolling>
					<position>
						<x>500</x>
						<y>500</y>
					</position>
					<position>
						<x>1000</x>
						<y>500</y>
					</position>
					<position>
						<x>1000</x>
						<y>1000</y>
					</position>
					<position>
						<x>500</x>
						<y>1000</y>
					</position>
				</patrolling>	
			</enemy>
		</enemies>
	</room>
	
	<room rId="4" width="1500" height="1500">
		<name>Room 4 - There we go - kill all enemies in this room!</name>
		
		<design>
			<background>Background_Stone</background>
			<walls>Wall_Stone</walls>
			<portals>
				<portal pIdRef="110">
					<position>
						<x>750</x>
						<y>1300</y>
					</position>
				</portal>		
			</portals>
			<movableobject>
				<position>
					<x>200</x>
					<y>600</y>
				</position>
				<!-- ATM modeltype 'hayBale' is the only one that is supported -->
				<model>hayBale</model> 
			</movableobject>
		</design>

		<enemies>
			<enemy type="battledroid" viewdirection="east">
				<position>
					<x>200</x>
					<y>500</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="east">
				<position>
					<x>200</x>
					<y>750</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="east">
				<position>
					<x>200</x>
					<y>1000</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="west">
				<position>
					<x>1300</x>
					<y>500</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="west">
				<position>
					<x>1300</x>
					<y>750</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="west">
				<position>
					<x>1300</x>
					<y>1000</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="south">
				<position>
					<x>500</x>
					<y>200</y>
				</position>
			</enemy>
			<enemy type="battledroid" viewdirection="south">
				<position>
					<x>1000</x>
					<y>200</y>
				</position>
			</enemy>
		</enemies>
	</room>
</level>
